### ISSUE TITLE
Апи ключи в коде

### ISSUE THREAD

**Issue by wellenc** [Slavian2015/ARBITRAGE_WEB_v.2#2]
Добрый день, Вячеслав

Обнаружил у вас ошибку - видимо, вы забыли удалить апи - ключи от бирж в файле test.py (input_hot_key и т.д.)

Это плохо, так как если ключи валидны кто угодно может обнулить ваш баланс путем покупки шиткоинов \ вывести средства с биржи, если это будет позволено апи

Рекомендую отозвать ключи и удалить их из кода, с уважением, wellenc

**Comment by Slavian2015** [comment]
Спасибо.

Сделано
